---
env:
  contexts:
  - name: "selenium-auth"
    urls:
    - "https://pp-services.signin.education.gov.uk/"
    includePaths:
    - "https://pp-services.signin.education.gov.uk/.*"
    excludePaths: []
    authentication:
      method: "script"
      parameters:
        script: "/zap/wrk/scripts/authenticate.js"
        scriptEngine: "Oracle Nashorn"
      verification:
        method: "poll"
        loggedInRegex: ".*Access DfE services.*"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: "https://pp-services.signin.education.gov.uk/my-services"
        pollPostData: ""
    sessionManagement:
      method: "script"
      parameters:
        script: "/zap/wrk/scripts/session.js"
        scriptEngine: "Oracle Nashorn"
    technology:
      exclude: []
    users:
    - name: "test"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- name: "passiveScan-config"
  type: "passiveScan-config"
  parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
- name: "script"
  type: "script"
  parameters:
    action: "add"
    type: "httpsender"
    engine: "Oracle Nashorn"
    name: "httpsender.js"
    file: "/zap/wrk/scripts/httpsender.js"
    target: ""
- parameters:
    action: "add"
    type: "httpsender"
    engine: "Oracle Nashorn"
    name: "LogMessages.js"
    file: "/zap/wrk/LogMessages.js"
  name: "script"
  type: "script"
- name: "script"
  type: "script"
  parameters:
    action: "add"
    type: "selenium"
    engine: Oracle Nashorn"
    name: "selenium.js"
    file: "/zap/wrk/scripts/selenium.js"
    target: ""